const ASSIGNMENT_STATUS = {
  PENDING: 'pending',
  ASSIGNED: 'assigned',
  ACCEPTED: 'accepted',
  PICKED_UP: 'picked_up',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

const ASSIGNMENT_STATUS_VALUES = Object.values(ASSIGNMENT_STATUS);

const DELIVERY_EARNING_STATUS = {
  PENDING: 'pending',
  CREDITED: 'credited',
};

const DELIVERY_EARNING_STATUS_VALUES = Object.values(DELIVERY_EARNING_STATUS);

const DELIVERY_OTP_TTL_SECONDS = 600; // 10 minutes
const DEFAULT_DELIVERY_EARNING_AMOUNT = 50;

module.exports = {
  ASSIGNMENT_STATUS,
  ASSIGNMENT_STATUS_VALUES,
  DELIVERY_EARNING_STATUS,
  DELIVERY_EARNING_STATUS_VALUES,
  DELIVERY_OTP_TTL_SECONDS,
  DEFAULT_DELIVERY_EARNING_AMOUNT,
};
