const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  GONE: 'GONE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  SELLER_OFFLINE: 'SELLER_OFFLINE',
  DELIVERY_NOT_AVAILABLE: 'DELIVERY_NOT_AVAILABLE',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // CR-002 — intelligent fulfillment
  FULFILLMENT_TIMEOUT: 'FULFILLMENT_TIMEOUT',
  NO_SELLER_AVAILABLE: 'NO_SELLER_AVAILABLE',
  WAREHOUSE_UNAVAILABLE: 'WAREHOUSE_UNAVAILABLE',
  COURIER_SERVICE_UNAVAILABLE: 'COURIER_SERVICE_UNAVAILABLE',
  INVENTORY_RESERVATION_FAILED: 'INVENTORY_RESERVATION_FAILED',
  FULFILLMENT_OFFER_EXPIRED: 'FULFILLMENT_OFFER_EXPIRED',
  MAP_SERVICE_UNAVAILABLE: 'MAP_SERVICE_UNAVAILABLE',
  REALTIME_CONNECTION_FAILED: 'REALTIME_CONNECTION_FAILED',
};

const DOMAIN_ERROR_STATUS = {
  [ERROR_CODES.OUT_OF_STOCK]: 409,
  [ERROR_CODES.PAYMENT_FAILED]: 402,
  [ERROR_CODES.ORDER_NOT_FOUND]: 404,
  [ERROR_CODES.SELLER_OFFLINE]: 409,
  [ERROR_CODES.DELIVERY_NOT_AVAILABLE]: 503,
  [ERROR_CODES.INVALID_TOKEN]: 401,

  // CR-002
  [ERROR_CODES.FULFILLMENT_TIMEOUT]: 503,
  [ERROR_CODES.NO_SELLER_AVAILABLE]: 503,
  [ERROR_CODES.WAREHOUSE_UNAVAILABLE]: 503,
  [ERROR_CODES.COURIER_SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.INVENTORY_RESERVATION_FAILED]: 409,
  [ERROR_CODES.FULFILLMENT_OFFER_EXPIRED]: 409,
  [ERROR_CODES.MAP_SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.REALTIME_CONNECTION_FAILED]: 503,
};

/**
 * Failures the customer may safely retry. Used by the fulfillment engine to
 * decide whether to escalate the fallback ladder or surface a terminal error.
 */
const RETRYABLE_ERROR_CODES = new Set([
  ERROR_CODES.FULFILLMENT_TIMEOUT,
  ERROR_CODES.NO_SELLER_AVAILABLE,
  ERROR_CODES.WAREHOUSE_UNAVAILABLE,
  ERROR_CODES.COURIER_SERVICE_UNAVAILABLE,
  ERROR_CODES.INVENTORY_RESERVATION_FAILED,
  ERROR_CODES.MAP_SERVICE_UNAVAILABLE,
  ERROR_CODES.REALTIME_CONNECTION_FAILED,
]);

const ERROR_CODE_TO_STATUS = {
  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.GONE]: 410,
  [ERROR_CODES.VALIDATION_ERROR]: 422,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.UPLOAD_ERROR]: 400,
};

module.exports = {
  ERROR_CODES,
  ERROR_CODE_TO_STATUS,
  DOMAIN_ERROR_STATUS,
  RETRYABLE_ERROR_CODES,
};
