const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  GONE: 'GONE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  SELLER_OFFLINE: 'SELLER_OFFLINE',
  DELIVERY_NOT_AVAILABLE: 'DELIVERY_NOT_AVAILABLE',
  INVALID_TOKEN: 'INVALID_TOKEN',
};

const DOMAIN_ERROR_STATUS = {
  [ERROR_CODES.OUT_OF_STOCK]: 409,
  [ERROR_CODES.PAYMENT_FAILED]: 402,
  [ERROR_CODES.ORDER_NOT_FOUND]: 404,
  [ERROR_CODES.SELLER_OFFLINE]: 409,
  [ERROR_CODES.DELIVERY_NOT_AVAILABLE]: 503,
  [ERROR_CODES.INVALID_TOKEN]: 401,
};

const ERROR_CODE_TO_STATUS = {
  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.GONE]: 410,
  [ERROR_CODES.VALIDATION_ERROR]: 422,
  [ERROR_CODES.RATE_LIMITED]: 429,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.UPLOAD_ERROR]: 400,
};

module.exports = {
  ERROR_CODES,
  ERROR_CODE_TO_STATUS,
  DOMAIN_ERROR_STATUS,
};
