const PLATFORM_SETTING_KEYS = {
  PLATFORM_NAME: 'platformName',
  SUPPORT_EMAIL: 'supportEmail',
  HELPLINE: 'helpline',
  GST: 'gst',
  PLATFORM_FEE: 'platformFee',
  PACKAGING_FEE: 'packagingFee',
  MIN_ORDER_AMOUNT: 'minOrderAmount',
  MAX_DELIVERY_RADIUS_KM: 'maxDeliveryRadiusKm',
  COD_ENABLED: 'codEnabled',
  COD_HANDLING_FEE: 'codHandlingFee',
  EXPRESS_SURCHARGE: 'expressSurcharge',
  RAZORPAY_ENABLED: 'razorpayEnabled',
  QUICK_COMMERCE_ENABLED: 'quickCommerceEnabled',
  ECOMMERCE_ENABLED: 'ecommerceEnabled',
  FREE_SHIPPING_THRESHOLD: 'freeShippingThreshold',
  DEFAULT_DELIVERY_CHARGE: 'defaultDeliveryCharge',
};

const DEFAULT_PLATFORM_SETTINGS = {
  [PLATFORM_SETTING_KEYS.PLATFORM_NAME]: 'Mithilakart',
  [PLATFORM_SETTING_KEYS.SUPPORT_EMAIL]: 'support@mithilakart.com',
  [PLATFORM_SETTING_KEYS.HELPLINE]: '+91 1800 123 4567',
  [PLATFORM_SETTING_KEYS.GST]: '',
  [PLATFORM_SETTING_KEYS.PLATFORM_FEE]: 0,
  [PLATFORM_SETTING_KEYS.PACKAGING_FEE]: 0,
  [PLATFORM_SETTING_KEYS.MIN_ORDER_AMOUNT]: 0,
  [PLATFORM_SETTING_KEYS.MAX_DELIVERY_RADIUS_KM]: 25,
  [PLATFORM_SETTING_KEYS.COD_ENABLED]: true,
  [PLATFORM_SETTING_KEYS.COD_HANDLING_FEE]: 0,
  [PLATFORM_SETTING_KEYS.EXPRESS_SURCHARGE]: 0,
  [PLATFORM_SETTING_KEYS.RAZORPAY_ENABLED]: true,
  [PLATFORM_SETTING_KEYS.QUICK_COMMERCE_ENABLED]: true,
  [PLATFORM_SETTING_KEYS.ECOMMERCE_ENABLED]: true,
  [PLATFORM_SETTING_KEYS.FREE_SHIPPING_THRESHOLD]: 500,
  [PLATFORM_SETTING_KEYS.DEFAULT_DELIVERY_CHARGE]: 39,
};

const PLATFORM_CONFIG_CACHE_KEY = 'cache:platform:config';
const PLATFORM_CONFIG_CACHE_TTL = 60;

module.exports = {
  PLATFORM_SETTING_KEYS,
  DEFAULT_PLATFORM_SETTINGS,
  PLATFORM_CONFIG_CACHE_KEY,
  PLATFORM_CONFIG_CACHE_TTL,
};
